Repository oracle-devrel/oci-terraform-genai-llm-on-gpuvms, pull requests merged in 2024-05, with the labels that each got.

#1 dev release
  .github/workflows/banned_file_changes_pr.yml
  .github/workflows/cla.yml
  .github/workflows/license_audit.yml
  .github/workflows/release-zip-file.yml
  .github/workflows/repolinter.yml
  .github/workflows/sonarcloud.yml
  .gitignore
  README.md
  apigateway.tf
  cloud-init/bootstrap
  compute.tf
  datasource.tf
  locals.tf
  output.tf
  provider.tf
  scripts/default.svc
  scripts/openai.svc
  scripts/setup.sh
  tag.tf
  tls.tf
  variables.tf
  vcn.tf
Labels: OCA Required

#2 Dev
  README.md
  images/a10_Custom_Inference.jpg
Labels: OCA Required

#4 BugB001-Fix
  README.md
  img/a10_Custom_Inference.jpg
  img/api_keys.PNG
  scripts/setup.sh
Labels: OCA Required

#5 feat: updated errors
  README.md
  img/api_keys.PNG
  scripts/setup.sh
Labels: documentation, enhancement

#6 Fixed the previous PR errors /updated readme
  README.md
  scripts/setup.sh
Labels: OCA Required

#8 Dev
  README.md
  scripts/api_gw_llm.py
  scripts/completions_llm.py
  scripts/requirements.txt
Labels: documentation, enhancement, OCA Verified
